## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------
server:
  port: 8082

alpha:
  server:
    host: 0.0.0.0
    port: 8081

spring:
  datasource:
    initialization-mode: always
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: 0.0.0.0
      port: 8500
      discovery:
        serviceName: {spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        instanceId: ${spring.application.name}-${alpha.server.host}-${random.value}
        tags: alpha-server-host=${alpha.server.host},alpha-server-port=${alpha.server.port}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://192.168.0.5:8761/eureka
  instance:
    metadataMap:
      servicecomb-alpha-server-port: ${alpha.server.port}
      servicecomb-alpha-server: ${alpha.server.host}:${alpha.server.port}
      prefer-ip-address: true
      hostname: 127.0.0.1


management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: ssl
alpha:
  server:
    ssl:
      enable: true
      cert: server.crt
      key: server.pem
      mutualAuth: true
      clientCert: client.crt
        
---
spring:
  profiles: prd
  datasource:
    username: saga
    password: password
    url: jdbc:postgresql://postgresql.servicecomb.io:5432/saga?useSSL=false
    platform: postgresql
    continue-on-error: false
  jpa:
    properties:
      eclipselink:
        ddl-generation: none

---
spring:
  profiles: mysql
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/saga?useSSL=false
    platform: mysql
    continue-on-error: false
    driverclassname: com.mysql.jdbc.Driver
  jpa:
    properties:
      eclipselink:
        ddl-generation: none