spring:
  application:
    name: eureka_service1
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
    instance-id: 1
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1:8761/eureka
---
spring:
  application:
    name: eureka_service2
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
    instance-id: 2
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2:8762/eureka,http://eureka1:8761/eureka

